$(document).ready(function()
{
	if($('#element_12_1').prop("checked"))
   		$('#grpname').show();
   	else
   		$('#grpname').hide();
   	if($('#element_13_1_1').prop("checked"))
   		$('#primary').show();
   	else
   		$('#primary').hide();
   	if($('#element_13_2_1').prop("checked"))
   		$('#secondary').show();
   	else
   		$('#secondary').hide();
   	if($('#element_13_3_1').prop("checked"))
   		$('#tertiary').show();
   	else
   		$('#tertiary').hide();
   	if($('#element_14_1').prop("checked"))
   		$('#activity').show();
   	else
   		$('#activity').hide();
	$('#group').change(function()
	{
   	   	if($('#element_12_1').prop("checked"))
	   		$('#grpname').show();
	   	else
	   		$('#grpname').hide();
	});
	$('#prim').change(function()
	{
   	   	if($('#element_13_1_1').prop("checked"))
	   		$('#primary').show();
	   	else
	   		$('#primary').hide();
	});
	$('#seco').change(function()
	{
   	   	if($('#element_13_2_1').prop("checked"))
	   		$('#secondary').show();
	   	else
	   		$('#secondary').hide();
	});
	$('#tert').change(function()
	{
   	   	if($('#element_13_3_1').prop("checked"))
			$('#tertiary').show();
		else
			$('#tertiary').hide();
	});
	$('#migrate').change(function()
	{
   	   	if($('#element_14_1').prop("checked"))
   			$('#activity').show();
   		else
   			$('#activity').hide();
	});
});
